pipeline:
  name: "ramyaPiplinePipe1"
  identifier: "ramyaPiplinePipe1"
  template:
    templateRef: "ramyaPipeline1"
    versionLabel: "1"
    templateInputs:
      stages:
      - stage:
          identifier: "gf"
          template:
            templateInputs:
              type: "Deployment"
              spec:
                execution:
                  steps:
                  - step:
                      identifier: "rwer"
                      template:
                        templateInputs:
                          type: "ShellScript"
                          timeout: "<+input>"
                          spec:
                            source:
                              type: "Inline"
                              spec:
                                script: "<+input>.allowedValues(2,3,4,5)"
  tags: {}
  projectIdentifier: "njh"
  orgIdentifier: "default"
