pipeline:
  name: rew
  identifier: rew
  projectIdentifier: njh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: gdf
        identifier: gdf
        template:
          templateRef: demoStage
          versionLabel: "1"
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: rew
                      template:
                        templateInputs:
                          type: ShellScript
                          spec:
                            source:
                              type: Inline
                              spec:
                                script: <+input>
                            environmentVariables:
                              - name: rw3rwe
                                type: String
                                value: <+input>
                              - name: r34
                                type: String
                                value: <+input>
                              - name: yrtyr
                                type: String
                                value: <+input>
                              - name: tre
                                type: String
                                value: <+input>
                              - name: gr
                                type: String
                                value: <+input>
                          timeout: <+input>
