pipeline:
  name: "test"
  identifier: "test"
  template:
    templateRef: "pipeline111111"
    versionLabel: "1"
    templateInputs:
      stages:
      - stage:
          identifier: "gdfg"
          template:
            templateInputs:
              type: "Approval"
              spec:
                execution:
                  steps:
                  - step:
                      identifier: "das"
                      template:
                        templateInputs:
                          type: "ShellScript"
                          spec:
                            source:
                              type: "Inline"
                              spec:
                                script: "<+input>"
  tags: {}
  projectIdentifier: "njh"
  orgIdentifier: "default"
