pipeline:
  name: vf
  identifier: vf
  projectIdentifier: njh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dw
        identifier: dw
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: dw
                  identifier: dw
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
